# Generated by Django 3.2.10 on 2022-01-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_wordpressmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordpressmapping',
            name='wp_post_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
