# Generated by Django 3.2.10 on 2022-04-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_wordpressmapping_wp_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='add_toc',
            field=models.BooleanField(default=False, help_text='A TOC can be auto-generated', verbose_name='Display TOC (Table Of Contents)'),
        ),
    ]
