# Generated by Django 3.2.13 on 2022-05-30 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_blogindexpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='authors',
            field=models.CharField(blank=True, help_text='Mention author(s) by the name to be displayed', max_length=255, null=True, verbose_name='author(s)'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_pages', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
    ]
