# Generated by Django 3.2.13 on 2022-06-06 20:44

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_migrate_old_images'),
        ('blog', '0009_alter_blogcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body_richtext',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='body (HTML)'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Header image'),
        ),
        migrations.AlterField(
            model_name='wordpressmapping',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mappings', to='images.customimage', verbose_name='Wagtail image'),
        ),
    ]
