# Generated by Django 3.2.9 on 2021-12-01 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, help_text='The main contents of the page', verbose_name='body')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ArchivePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('title_en', models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title')),
                ('title_ar', models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title')),
                ('title_fr', models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title')),
                ('title_de', models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title')),
                ('seo_title_en', models.CharField(blank=True, help_text='The name of the page displayed on search engine results as the clickable headline.', max_length=255, null=True, verbose_name='title tag')),
                ('seo_title_ar', models.CharField(blank=True, help_text='The name of the page displayed on search engine results as the clickable headline.', max_length=255, null=True, verbose_name='title tag')),
                ('seo_title_fr', models.CharField(blank=True, help_text='The name of the page displayed on search engine results as the clickable headline.', max_length=255, null=True, verbose_name='title tag')),
                ('seo_title_de', models.CharField(blank=True, help_text='The name of the page displayed on search engine results as the clickable headline.', max_length=255, null=True, verbose_name='title tag')),
                ('search_description_en', models.TextField(blank=True, help_text='The descriptive text displayed underneath a headline in search engine results.', null=True, verbose_name='meta description')),
                ('search_description_ar', models.TextField(blank=True, help_text='The descriptive text displayed underneath a headline in search engine results.', null=True, verbose_name='meta description')),
                ('search_description_fr', models.TextField(blank=True, help_text='The descriptive text displayed underneath a headline in search engine results.', null=True, verbose_name='meta description')),
                ('search_description_de', models.TextField(blank=True, help_text='The descriptive text displayed underneath a headline in search engine results.', null=True, verbose_name='meta description')),
                ('wordpress_post_id', models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
                ('organization_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='organization type')),
                ('country', django_countries.fields.CountryField(blank=True, default='', max_length=746, multiple=True, verbose_name='country')),
                ('short_description', models.TextField(blank=True, null=True)),
                ('description', wagtail.core.fields.RichTextField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_archives', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='LocationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('title_en', models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title')),
                ('title_ar', models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title')),
                ('title_fr', models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title')),
                ('title_de', models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title')),
                ('seo_title_en', models.CharField(blank=True, help_text='The name of the page displayed on search engine results as the clickable headline.', max_length=255, null=True, verbose_name='title tag')),
                ('seo_title_ar', models.CharField(blank=True, help_text='The name of the page displayed on search engine results as the clickable headline.', max_length=255, null=True, verbose_name='title tag')),
                ('seo_title_fr', models.CharField(blank=True, help_text='The name of the page displayed on search engine results as the clickable headline.', max_length=255, null=True, verbose_name='title tag')),
                ('seo_title_de', models.CharField(blank=True, help_text='The name of the page displayed on search engine results as the clickable headline.', max_length=255, null=True, verbose_name='title tag')),
                ('search_description_en', models.TextField(blank=True, help_text='The descriptive text displayed underneath a headline in search engine results.', null=True, verbose_name='meta description')),
                ('search_description_ar', models.TextField(blank=True, help_text='The descriptive text displayed underneath a headline in search engine results.', null=True, verbose_name='meta description')),
                ('search_description_fr', models.TextField(blank=True, help_text='The descriptive text displayed underneath a headline in search engine results.', null=True, verbose_name='meta description')),
                ('search_description_de', models.TextField(blank=True, help_text='The descriptive text displayed underneath a headline in search engine results.', null=True, verbose_name='meta description')),
                ('name', models.CharField(help_text='Typically a city name or region', max_length=255, verbose_name='location name')),
                ('name_en', models.CharField(help_text='Typically a city name or region', max_length=255, null=True, verbose_name='location name')),
                ('name_ar', models.CharField(help_text='Typically a city name or region', max_length=255, null=True, verbose_name='location name')),
                ('name_fr', models.CharField(help_text='Typically a city name or region', max_length=255, null=True, verbose_name='location name')),
                ('name_de', models.CharField(help_text='Typically a city name or region', max_length=255, null=True, verbose_name='location name')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='country')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ArchivePageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivepages', to='archive.locationpage')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='archive.archivepage')),
            ],
            options={
                'unique_together': {('page', 'location')},
            },
        ),
    ]
