# Generated by Django 3.2.9 on 2021-11-22 00:15

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('home', '0005_article_body'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveIndexPage',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.article')),
            ],
            options={
                'abstract': False,
            },
            bases=('home.article',),
        ),
        migrations.CreateModel(
            name='ArchivePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('wordpress_post_id', models.PositiveSmallIntegerField(blank=None, editable=False, null=True)),
                ('organization_type', models.CharField(blank=None, max_length=255, null=True, verbose_name='organization type')),
                ('country', django_countries.fields.CountryField(blank=None, max_length=2, null=True, verbose_name='country')),
                ('short_description', models.TextField(blank=None, null=True)),
                ('description', wagtail.core.fields.RichTextField()),
                ('author', models.ForeignKey(blank=True, limit_choices_to=blog.models.limit_author_choices, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_archives', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='LocationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('name', models.CharField(help_text='Typically a city name or region', max_length=255, verbose_name='location name')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='country')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ArchivePageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivepages', to='archive.locationpage')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='archive.archivepage')),
            ],
            options={
                'unique_together': {('page', 'location')},
            },
        ),
    ]
