# Generated by Django 3.2.10 on 2021-12-23 01:00

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivepage',
            name='description_ar',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='archivepage',
            name='description_de',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='archivepage',
            name='description_en',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='archivepage',
            name='description_fr',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
    ]
