# Generated by Django 3.2.13 on 2022-07-20 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_create_archiveindex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivepage',
            name='short_description',
        ),
    ]
